const screens=[...document.querySelectorAll('.screen')];const state={audio:false};
const $=s=>document.querySelector(s);
function show(name){screens.forEach(s=>s.classList.toggle('active',s.dataset.screen===name));window.scrollTo({top:0,behavior:'smooth'});if(name==='complete')revealClassification();if(name==='birthday')launchCelebration(70);if(name==='final')launchCelebration(150)}
function beep(freq=440,dur=.08,type='sine',gain=.025){try{if(!state.audio){state.ctx=new(window.AudioContext||window.webkitAudioContext)();state.audio=true}const o=state.ctx.createOscillator(),g=state.ctx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain,state.ctx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,state.ctx.currentTime+dur);o.connect(g);g.connect(state.ctx.destination);o.start();o.stop(state.ctx.currentTime+dur)}catch(e){}}
function typeLog(lines){const box=$('#bootLog');let i=0;function next(){if(i>=lines.length){$('#enterBtn').classList.remove('hidden');return}const p=document.createElement('div');p.textContent='> '+lines[i];box.appendChild(p);beep(520+i*55,.045,'square',.018);i++;setTimeout(next,360)}next()}
(function boot(){const bar=$('#bootProgress');let p=0;const timer=setInterval(()=>{p+=Math.random()*17+7;if(p>=100){p=100;clearInterval(timer);typeLog(['Establishing secure friendship channel...','Searching subject database...','Subject found: RATUL','Birthday signature verified: 10.09.2026','Protocol ready.'])}bar.style.width=p+'%'},170)})();
$('#enterBtn').addEventListener('click',()=>{beep(180,.18,'sawtooth',.04);show('profile')});
document.addEventListener('click',e=>{const b=e.target.closest('[data-next]');if(b){beep(680,.07,'triangle',.025);show(b.dataset.next)}});
document.querySelectorAll('.choice').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.choice').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');const p=btn.dataset.path;const messages={medical:'SIMULATION RESULT: Doctor Ratul.exe detected. Please prescribe common sense.',engineering:'SIMULATION RESULT: Engineer Ratul.exe detected. System may require debugging.',buet:'TARGET LOCKED: BUET CRACK PROTOCOL ACTIVE. Still a dream. Still possible. Keep going, bro.',unknown:'SYSTEM RESPONSE: Same bro. Nobody has the whole map. Figure it out one step at a time.'};const box=$('#futureResult');box.textContent=messages[p];box.classList.remove('hidden');$('#futureContinue').classList.remove('hidden');beep(760,.1,'triangle',.03)}));
function revealClassification(){const c=$('#classification');c.innerHTML='CLASSIFICATION:<br><strong></strong><br><span>STATUS: FRIEND.</span>';const out=c.querySelector('strong'),word='RATUL';let i=0;const timer=setInterval(()=>{out.textContent=word.slice(0,++i);beep(320+i*45,.045,'square',.018);if(i===word.length){clearInterval(timer);setTimeout(()=>$('#birthdayReveal').classList.remove('hidden'),650)}},180)}
function launchCelebration(n=70){const root=$('#confetti');root.innerHTML='';for(let i=0;i<n;i++){const p=document.createElement('i');p.className='piece';p.style.left=Math.random()*100+'vw';p.style.setProperty('--x',(Math.random()*80-40)+'vw');p.style.animationDuration=(2.2+Math.random()*2.5)+'s';p.style.animationDelay=(Math.random()*.7)+'s';p.style.opacity=.7+Math.random()*.3;root.appendChild(p)}setTimeout(()=>root.innerHTML='',6000)}
$('#finishBtn').addEventListener('click',()=>{beep(880,.12,'sine',.04);show('final')});$('#replayBtn').addEventListener('click',()=>location.reload());
setInterval(()=>{$('#clock').textContent=new Date().toLocaleTimeString('en-GB',{hour12:false})},1000);document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='r'&&e.target.tagName!=='INPUT')location.reload()});